apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: microshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microshop-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: orders_db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: microshop-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microshop-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: microshop
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
