# order-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: us-central1-docker.pkg.dev/microshop-470313/microshop-backend/order-service:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: microshop-config
            - secretRef:
                name: microshop-secret
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microshop
spec:
  selector:
    app: order-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
