# user-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: us-central1-docker.pkg.dev/microshop-470313/microshop-backend/user-service:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: microshop-config
            - secretRef:
                name: microshop-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microshop
spec:
  selector:
    app: user-service
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
